name: Build and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci \
          npx --no-install next build \
          npx --no-install next export
        # env:
        #   CI: true
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          # name: build
          path: out
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to S3
        # with:
        #   args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
          # SOURCE_DIR: 'out'      # optional: defaults to entire repository
        run: |
          aws s3 cp \
          --recursive --acl public-read --follow-symlinks --delete --exclude '.git/*' \
          --region eu-west-2 \
          ./out s3://${{ secrets.AWS_S3_BUCKET }}